Edited GUI Frames
vlyandra/PokerProjectCapstone pull request #10
Opened 2019-04-27 18:37 UTC by Poockins

Made corrections to the GUI frames, added in authors, sizing and formatting. Welcome Screen needs to be centered.

2019-04-27 19:08 UTC, vlyandra requested changes
LGTM other than one thing, see review.

2019-04-27 19:08 UTC, vlyandra commented on src/main/java/calculator/PokerCalculator.java
> +import calculator.Cards;
This should be unnecessary because they're in the same package.

2019-04-27 21:37 UTC, Poockins commented on src/main/java/calculator/PokerCalculator.java
> +import calculator.Cards;
For some reason, I was not able to get the code to run except when I implemented this import. I also had to move the "package calculator;" above all the imports for it to run. Not really sure why

2019-04-28 00:21 UTC, vlyandra commented on src/main/java/calculator/PokerCalculator.java
> +import calculator.Cards;
Package declarations always need to be the first source line in Java.

2019-04-28 00:22 UTC, vlyandra approved these changes

2019-04-28 00:22 UTC, merged