Functionaity ready
vlyandra/PokerProjectCapstone pull request #19
Opened 2019-05-03 01:08 UTC by tcorea

I have created the Poker Evaluator class that evaluates a the users hand and determines its value whether it is a royal flush or pair, etc. It will be used by the PokerChart class which has most/common poker odds that exist in the game. The poker calculator gets information from the user about its hand and community board and tries to then calculates the probability using outs, loss, and  unkowns and turning it into a ratio and then converts that into a percentage which is our output. Tostring method will have output. but must call calculations method to get it.
I was able to come with this based off the links given to me about the poker chart. Also, I want try to make it more intense with a complex algorithm hopefully for final. two junit test cases available. 
~Thomas Corea

2019-05-03 14:42 UTC, vlyandra requested changes
- Please lint your code, especially regarding bracket use/placement.
- A lot of your method Javadocs do not have any @param information, and the @return information is very vague
- I'm not sure what's going on with PokerCalculatorTest. Even if you're going for TDD they should still test something, even if the tests don't all pass yet (at which point, they shouldn't be included as part of the test suite)

2019-05-03 14:42 UTC, vlyandra commented on src/main/java/calculator/PokerChart.java
> +/**
Javadocs must be the beginning of the file.

2019-05-03 14:42 UTC, vlyandra commented on src/main/java/calculator/PokerChart.java
> +   * @return boolean value
@return statements should be descriptive of what they're returning. `value` doesn't tell the next person looking at this code what the return means.

2019-05-03 14:42 UTC, vlyandra commented on src/main/java/calculator/PokerChart.java
> +    if (!(evaluator.hasPair(userCards, communityCards)))
you can just `return !(evaluator.hasPair(userCards, communityCards))` here

2019-05-03 14:42 UTC, vlyandra commented on src/main/java/calculator/PokerChart.java
> +    if (evaluator.hasTwoPairs(userCards, communityCards)) {
This can be replaced with `return evaluator.hasTwoPairs(userCards, communityCards)`

2019-05-03 14:42 UTC, vlyandra commented on src/main/java/calculator/PokerChart.java
> +    for (Cards card : communityCards) {
These two for loops could be combined, since you're returning if either of them is true at any point.

2019-05-03 14:42 UTC, vlyandra commented on src/main/java/calculator/PokerEvaluator.java
> +    int num_OfPairs, num_OfPairs1;
Java variable names should be lowerCamelCase, no underscores.

2019-05-03 14:42 UTC, vlyandra commented on src/main/java/calculator/PokerEvaluator.java
> +    if (hasStraight(userCards, communityCards) && hasFlush(userCards, communityCards))
`return hasStraight(userCards, communityCards) && hasFlush(userCards, communityCards)` is sufficient here

2019-05-03 14:42 UTC, vlyandra commented on src/main/java/calculator/PokerEvaluator.java
> +    if (hasThreeOfKind(userCards, communityCards) && hasPair(userCards, communityCards))
See above, `return hasThreeOfKind(userCards, communityCards) && hasPair(userCards, communityCards)`

2019-05-03 14:42 UTC, vlyandra commented on src/main/java/calculator/PokerEvaluator.java
> +   * Checks to see if you have a pair.
This javadoc appears to be incorrect. This checks for two pairs, yes?

2019-05-03 14:42 UTC, vlyandra commented on src/main/java/calculator/PokerChart.java
> +    if (evaluator.hasPair(userCards, communityCards))
This doesn't assure a pocket pair, since `evaluator.hasPair` will return true if the cards on the board also allow for a pair.

2019-05-03 14:42 UTC, vlyandra commented on src/main/java/calculator/PokerEvaluator.java
> +      return false;// impossible to have two pairs if your only two cards are same
But you can have two pairs if there's a pair on the board and you have a pocket pair, right?

2019-05-03 14:42 UTC, vlyandra commented on src/main/java/calculator/PokerEvaluator.java
> +      if (suitCounter == 5)
While unlikely it is possible that there can be more than 5 cards of the same suit within the 7 available cards.

2019-05-03 14:42 UTC, vlyandra commented on src/main/java/calculator/PokerEvaluator.java
> +    boolean aceCard, kingCard, queenCard, jackCard, tenCard;// royal flush
A data structure would be nice here instead of 5 separate variables.

2019-05-03 14:42 UTC, vlyandra commented on src/test/java/calculator/PokerCalculatorTest.java
> +  @BeforeClass
We use JUnit 5, please use JUnit 5 terminology.

2019-05-03 14:42 UTC, vlyandra commented on src/test/java/calculator/PokerCalculatorTest.java
> +  public void setUp() throws Exception {
It looks like you're using mostly the same cards everywhere, wouldn't it be easier to just make them here? You're also doing a reset before every test, that could happen here too.

2019-05-03 14:42 UTC, vlyandra commented on src/test/java/calculator/PokerEvaluatorTest.java
> +  public void testHasPair() {
Is there a reason you don't reset here?

2019-05-03 14:42 UTC, vlyandra commented on src/test/java/calculator/PokerEvaluatorTest.java
> +    // another test
If it's another test, it should be written as another, separate test.

2019-05-03 14:42 UTC, vlyandra commented on src/test/java/calculator/PokerCalculatorTest.java
> +
There seem to be no assertions used at all. Is there a reason these tests don't test anything?

2019-05-03 14:42 UTC, vlyandra commented on src/test/java/calculator/PokerEvaluatorTest.java
> +
Again, the card resets could all be done here or in @AfterEach

2019-05-03 14:42 UTC, vlyandra commented on src/test/java/calculator/PokerEvaluatorTest.java
> +    calcObj.resetUserHand();
This is two tests, right? They should be separated out into separate tests.

2019-05-03 14:42 UTC, vlyandra commented on src/test/java/calculator/PokerEvaluatorTest.java
> +  private PokerCalculator calcObj = new PokerCalculator();
If looks to me like you're only using calcObj to hold cards here? It's preferable to only use outside classes that are strictly necessary, and this creates an unnecessary dependency.

2019-05-03 14:42 UTC, vlyandra commented on src/test/java/calculator/PokerCalculatorTest.java
> +import org.junit.Test;
We use JUnit 5, please use JUnit 5 packages from `org.junit.jupiter.api`

2019-05-03 14:42 UTC, vlyandra commented on src/test/java/calculator/PokerEvaluatorTest.java
> +    assertTrue(calcEval.hasPair(calcObj.getUserCards(), calcObj.getCommunityCards()));
If you are making multiple test cases in a test, they need to be separate tests.

2019-05-03 14:42 UTC, vlyandra commented on src/main/java/calculator/PokerCalculator.java
> +   private int handValue;// 1-10 . 10 being the most valuable
Where is this used, other than assigned in the constructor?

2019-05-03 14:45 UTC, vlyandra commented
Also, this branch is way behind master. Please resolve the conflicts.

2019-05-04 01:52 UTC, tcorea commented on src/test/java/calculator/PokerCalculatorTest.java
> +import org.junit.Test;
Ok I will have to re-install entire different IDE. So ill work on that.

2019-05-04 02:29 UTC, vlyandra commented on src/test/java/calculator/PokerCalculatorTest.java
> +import org.junit.Test;
Your IDE should have nothing to do with this. Maven automatically manages the JUnit 5 dependency.

2019-05-04 02:35 UTC, vlyandra requested changes
Please at least address all of the requested changes. There are some still unresolved.

Also, your branch conflicts hard with master. Please resolve the merge conflicts.

2019-05-04 18:27 UTC, tcorea commented on src/main/java/calculator/PokerChart.java
> +   * @return boolean value
I made @return more descriptive

2019-05-04 18:28 UTC, tcorea commented on src/main/java/calculator/PokerChart.java
> +    if (!(evaluator.hasPair(userCards, communityCards)))
I repaired the unnecessary coding.

2019-05-04 18:28 UTC, tcorea commented on src/main/java/calculator/PokerChart.java
> +    if (evaluator.hasTwoPairs(userCards, communityCards)) {
I made the adjustments to the statements above.

2019-05-04 18:29 UTC, tcorea commented on src/test/java/calculator/PokerEvaluatorTest.java
> +    calcObj.resetUserHand();
This will be resolved later since i have to find a new IDE

2019-05-04 18:29 UTC, tcorea commented on src/test/java/calculator/PokerEvaluatorTest.java
> +  private PokerCalculator calcObj = new PokerCalculator();
will change later once i update to Junit 5

2019-05-04 18:31 UTC, tcorea commented on src/test/java/calculator/PokerCalculatorTest.java
> +import org.junit.Test;
> Your IDE should have nothing to do with this. Maven automatically manages the JUnit 5 dependency.

Well im using Eclipse NEon so im not sure what you mean by this statement. According to the Eclipse website I have to install Eclipse Oxygen or later version

2019-05-04 18:31 UTC, tcorea commented on src/test/java/calculator/PokerEvaluatorTest.java
> +    assertTrue(calcEval.hasPair(calcObj.getUserCards(), calcObj.getCommunityCards()));
will resolve when i update eclipse

2019-05-04 18:32 UTC, tcorea commented on src/main/java/calculator/PokerChart.java
> +/**
I thought you said earlier that packages go at the top first ? sorry

2019-05-04 18:32 UTC, tcorea commented on src/main/java/calculator/PokerCalculator.java
> +   private int handValue;// 1-10 . 10 being the most valuable
it has been removed.

2019-05-04 18:33 UTC, tcorea commented
> Please at least address all of the requested changes. There are some still unresolved.
> 
> Also, your branch conflicts hard with master. Please resolve the merge conflicts.

ok I think everything is resolved for now.

2019-05-04 18:52 UTC, vlyandra commented
There are unresolved change requests still, eg https://github.com/vlyandra/PokerProjectCapstone/pull/19#discussion_r280775201 and the branch still had serious conflicts with master

2019-05-04 18:53 UTC, vlyandra commented on src/main/java/calculator/PokerChart.java
> +/**
Package declarations must be the first source line. Javadocs go above.

2019-05-04 18:53 UTC, vlyandra commented on src/main/java/calculator/PokerChart.java
> +/**
Package declarations must be the first source line. Javadocs go above.

2019-05-04 18:55 UTC, vlyandra commented on src/main/java/calculator/PokerChart.java
> +   * @return boolean value
Where?

2019-05-04 18:56 UTC, vlyandra commented on src/main/java/calculator/PokerChart.java
> +   * @return boolean value
Where?

2019-05-04 18:56 UTC, tcorea commented
> There are unresolved change requests still, eg [#19 (comment)](https://github.com/vlyandra/PokerProjectCapstone/pull/19#discussion_r280775201) and the branch still had serious conflicts with master

What does that mean ? I just made an adjustment. So I think its resolved. I found some instructions online. This is my first time using github for project or whatever so bare with me. THanks

2019-05-04 18:58 UTC, vlyandra commented
Ah, I hadn’t caught your most recent commit.

2019-05-04 18:58 UTC, tcorea commented
> Ah, I hadn’t caught your most recent commit.

no worries did that fix it ?

2019-05-04 19:06 UTC, vlyandra commented
It’ll merge, but somehow you’ve touched every file and you’re actually reverting some previous progress. I can’t approve this without losing functionality.

2019-05-04 19:07 UTC, vlyandra commented
Did you check the link in the README with git instructions?

2019-05-04 19:09 UTC, tcorea commented
> Did you check the link in the README with git instructions?
yes I did it read it. So do I cancel this merge and just do another one ?

2019-05-04 19:17 UTC, tcorea commented
> It’ll merge, but somehow you’ve touched every file and you’re actually reverting some previous progress. I can’t approve this without losing functionality.

should i close this pull request?

2019-05-10 00:07 UTC, vlyandra approved these changes
Fixed most of the remaining issues I found. Approving so we can get this merged.

2019-05-10 00:07 UTC, vlyandra commented on src/main/java/calculator/PokerEvaluator.java
> +       if (suitCounter == 5)
A user can have a flush with their hand and all of the community cards by having 5 *or more* of the same suit total.

2019-05-10 00:07 UTC, merged