Update PokerCalculator.java
vlyandra/PokerProjectCapstone pull request #8
Opened 2019-04-26 22:56 UTC by tcorea

2019-04-26 23:21 UTC, vlyandra requested changes
This code needs to be linted and fixed to adhere to the Google Java Style guide: https://google.github.io/styleguide/javaguide.html

Something I can see immediately is that the brace style is generally incorrect: https://google.github.io/styleguide/javaguide.html#s4.1-braces

I believe we also discussed using the two plus two strategy for probability calculation, using a lookup table, instead of the naive solution?

2019-04-26 23:21 UTC, vlyandra commented on src/main/java/calculator/PokerCalculator.java
> +
Did you remove the package declaration for a reason?

2019-04-26 23:21 UTC, vlyandra commented on src/main/java/calculator/PokerCalculator.java
>  	//This will produce the probability of winning.
Please use Javadoc comments.

2019-04-26 23:21 UTC, vlyandra commented on src/main/java/calculator/PokerCalculator.java
> +				else if(royalCards.contains(userCards.get(1)))
Is there a reason this isn't just a logical OR?

2019-04-26 23:30 UTC, vlyandra commented on src/main/java/calculator/PokerCalculator.java
>  	public boolean hasPair()
All of these hand evaluation functions should have tests.

2019-04-26 23:50 UTC, tcorea commented on src/main/java/calculator/PokerCalculator.java
> +				else if(royalCards.contains(userCards.get(1)))
i guess we can use or statement. I have some junit tests for this method and will test it out just to be sure. lol

2019-04-26 23:50 UTC, tcorea commented on src/main/java/calculator/PokerCalculator.java
>  	//This will produce the probability of winning.
ok i will make the corrections tonight

2019-04-26 23:50 UTC, tcorea commented on src/main/java/calculator/PokerCalculator.java
> +
no i dont think so maybe a mistake mistyped or something

2019-04-27 01:19 UTC, tcorea commented on src/main/java/calculator/PokerCalculator.java
>  	public boolean hasPair()
Yes I have tests for all of them. i've tested them before commiting and the pr. Do you need the junit test cases ?

2019-04-27 01:24 UTC, vlyandra commented on src/main/java/calculator/PokerCalculator.java
>  	public boolean hasPair()
Tests should always be committed with the code.

2019-04-27 01:56 UTC, tcorea commented
> This code needs to be linted and fixed to adhere to the Google Java Style guide: https://google.github.io/styleguide/javaguide.html
> 
> Something I can see immediately is that the brace style is generally incorrect: https://google.github.io/styleguide/javaguide.html#s4.1-braces
> 
> I believe we also discussed using the two plus two strategy for probability calculation, using a lookup table, instead of the naive solution?

yes i was gonna continue to come up with a ratio which in turn gets us a percentage, by finding the desirabe outcomes/unwanted outcomes. . I trying looking for a two plus two strategy but have a hard time coming up with a solution of sorts do you any good references for that strategy ?

2019-04-28 04:15 UTC, closed without merging